[package]
name = "epic"
version = "0.1.0"
authors = ["Huang.Weijie <wjhuang@live.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
git2 = "0.12"